language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package publishOnlyWhenOnMaster
scala:
  - 2.11.0
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
    - denys.shabalin@typesafe.com
env:
  global:
   - SCALAREFLECT_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAREFLECT_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "Gqy4yG33CwMmzNWDG88Vm1J0v41o0bCUAIumCXsupDQ724BpRmWqeq8kPUFYY37ZqK0rJ0GKcacvmN5yrESO+PQDoAoJfC/ZIVwtz/2Tul0NBracoj4gixTxxR3/Sz7Z232WaxDdVHa7qgeprA8OmSc8KJgbc3ypMzuTZy2jlL0="
   - secure: "Sq56bIOUkHb65JdY5DfHSdDd3HiEiKbNxv15BBQHHpLAYdYk07EB38e6A4q9UIlN01EHcB537pE4IECirMIKGhP9czN+1nvOspk1OXU6GJHHH2I6Bs6Jq3i3Cs3EQzqIG3ft/LNcqnm0Gx52KmBsu57FoWwTzW5g7pOErebp3E4="
